version: "3.8" 
services:
  nginx:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
    # defaults to 1 , but we are being explicit
    deploy:
      replicas: 1
    volumes:
    - type: bind
      source: ./nginx/ningx.conf
      target: /etc/nginx/nginx.conf
    depends-on: 
    - flask-app
  flask-app:
    image: stratcastor/flask-app:latest
    build: ./
    deploy:
      replicas: 3      